tunnel: __CF_TUNNEL_UUID__
credentials-file: /root/.cloudflared/__CF_TUNNEL_UUID__.json

ingress:
  - hostname: __CF_HOSTNAME__
    service: http://localhost:__CF_LOCAL_PORT__
  - service: http_status:404
